apiVersion: v1
kind: Service
metadata:
  name: ssservice
  namespace: default
  labels:
    app: statefulapp
spec:
  selector:
    app: statefulapp
  type: ClusterIP
  clusterIP: None
  ports:
  - name: web
    port: 8080
